services:
  - type: web
    name: ai-fashion-stylist-api
    env: node
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production